// Centralized car data for the Albanian car rental marketplace

import type { Car } from "./CarCard";

export const carsData: Car[] = [
  {
    id: 1,
    make: "Mercedes-Benz",
    model: "CLS 63 AMG",
    year: 2013,
    category: "Luxury",
    location: "Tirana",
    dailyRate: 150,
    weeklyRate: 900,
    currency: "EUR",
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    engine: "5.5L V8 Biturbo",
    horsepower: 557,
    licensePlate: "AB 051 TK",
    imageUrl:
      "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800&q=80",
    supplier: "AutoLux Albania",
    phone: "+355 69 123 4567",
    whatsapp: "+35569123456",
    email: "info@autolux.al",
    rating: 4.9,
    reviewCount: 38,
    featured: true,
    premium: true,
    tags: ["Airport Pickup", "Unlimited KM", "GPS"],
  },
  {
    id: 2,
    make: "Fiat",
    model: "Panda",
    year: 2021,
    category: "Economy",
    location: "Durrës",
    dailyRate: 25,
    weeklyRate: 150,
    currency: "EUR",
    transmission: "Manual",
    fuelType: "Petrol",
    seats: 5,
    imageUrl:
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
    supplier: "DurrësDrive",
    phone: "+355 52 234 5678",
    whatsapp: "+35552234567",
    email: "rentals@durresdrive.al",
    rating: 4.6,
    reviewCount: 64,
    featured: true,
    tags: ["Fuel Efficient", "City Car", "Free Cancellation"],
  },
  {
    id: 3,
    make: "Dacia",
    model: "Sandero",
    year: 2022,
    category: "Economy",
    location: "Durrës",
    dailyRate: 28,
    weeklyRate: 168,
    currency: "EUR",
    transmission: "Manual",
    fuelType: "Petrol",
    seats: 5,
    imageUrl:
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
    supplier: "BudgetRent Albania",
    phone: "+355 52 345 6789",
    whatsapp: "+35552345678",
    email: "book@budgetrent.al",
    rating: 4.5,
    reviewCount: 51,
    featured: true,
    tags: ["Best Value", "Long-term Available"],
  },
  {
    id: 4,
    make: "BMW",
    model: "X5",
    year: 2022,
    category: "SUV",
    location: "Tirana International Airport (TIA)",
    dailyRate: 120,
    weeklyRate: 720,
    currency: "EUR",
    transmission: "Automatic",
    fuelType: "Diesel",
    seats: 7,
    engine: "3.0L 6-cyl",
    horsepower: 340,
    imageUrl:
      "https://images.unsplash.com/photo-1622194991483-5a7a28a1c24a?w=800&q=80",
    supplier: "PremiumFleet TIA",
    phone: "+355 69 456 7890",
    whatsapp: "+35569456789",
    email: "tia@premiumfleet.al",
    rating: 4.8,
    reviewCount: 29,
    featured: true,
    tags: ["Airport Transfer", "7 Seats", "Climate Control"],
  },
  {
    id: 5,
    make: "Volkswagen",
    model: "Golf",
    year: 2023,
    category: "Economy",
    location: "Sarandë",
    dailyRate: 40,
    weeklyRate: 240,
    currency: "EUR",
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    imageUrl:
      "https://images.unsplash.com/photo-1471479917193-f00955256257?w=800&q=80",
    supplier: "RivieraRent",
    phone: "+355 85 567 8901",
    whatsapp: "+35585567890",
    email: "info@rivierarent.al",
    rating: 4.7,
    reviewCount: 45,
    tags: ["Riviera Road Trip", "Coastal Route", "Free Delivery"],
  },
  {
    id: 6,
    make: "Range Rover",
    model: "Sport",
    year: 2021,
    category: "SUV",
    location: "Vlorë",
    dailyRate: 180,
    weeklyRate: 1050,
    currency: "EUR",
    transmission: "Automatic",
    fuelType: "Diesel",
    seats: 5,
    engine: "3.0L SDV6",
    horsepower: 306,
    imageUrl:
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&q=80",
    supplier: "VlorëLux Cars",
    phone: "+355 33 678 9012",
    whatsapp: "+35533678901",
    email: "vip@vlorelux.al",
    rating: 4.9,
    reviewCount: 17,
    premium: true,
    tags: ["Off-road Ready", "Panoramic Roof", "Full Insurance"],
  },
  {
    id: 7,
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    category: "Economy",
    location: "Shkodër",
    dailyRate: 35,
    weeklyRate: 210,
    currency: "EUR",
    transmission: "Manual",
    fuelType: "Hybrid",
    seats: 5,
    imageUrl:
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
    supplier: "NorthAlbania Rentals",
    phone: "+355 22 789 0123",
    whatsapp: "+35522789012",
    email: "rental@northalbania.al",
    rating: 4.6,
    reviewCount: 33,
    tags: ["Eco Hybrid", "Low Emission", "Comfortable"],
  },
  {
    id: 8,
    make: "Porsche",
    model: "911 Cabriolet",
    year: 2020,
    category: "Convertible",
    location: "Sarandë",
    dailyRate: 250,
    weeklyRate: 1500,
    currency: "EUR",
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 2,
    engine: "3.0L Twin-Turbo",
    horsepower: 450,
    imageUrl:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
    supplier: "ExoticAlbania",
    phone: "+355 69 890 1234",
    whatsapp: "+35569890123",
    email: "exotic@exoticalbania.al",
    rating: 5.0,
    reviewCount: 12,
    premium: true,
    tags: ["Convertible", "Sports", "Riviera Drive"],
  },
];

export const categories = [
  {
    id: "coastal",
    title: "Coastal Road Trips",
    subtitle: "Cheap Car Rentals for the Albanian Riviera",
    icon: "🏖️",
    bgColor: "from-blue-500 to-teal-400",
    count: 45,
  },
  {
    id: "luxury",
    title: "Luxury & Sports Cars",
    subtitle: "Premium Vehicles in Tirana & Sarandë",
    icon: "💎",
    bgColor: "from-purple-600 to-indigo-500",
    count: 28,
  },
  {
    id: "airport",
    title: "Airport Transfers",
    subtitle: "Tirana International Airport (TIA)",
    icon: "✈️",
    bgColor: "from-gray-700 to-gray-900",
    count: 62,
  },
  {
    id: "economy",
    title: "Economy Cars",
    subtitle: "Budget-Friendly Options Across Albania",
    icon: "💰",
    bgColor: "from-green-500 to-emerald-400",
    count: 120,
  },
  {
    id: "suv",
    title: "SUVs & 4x4",
    subtitle: "Perfect for Mountain Exploration",
    icon: "🏔️",
    bgColor: "from-orange-500 to-red-400",
    count: 55,
  },
  {
    id: "chauffeur",
    title: "Car with Driver",
    subtitle: "Professional Chauffeur Services",
    icon: "👨‍✈️",
    bgColor: "from-crimson to-red-900",
    count: 30,
  },
];
